name: tygronai
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pytorch
  - pytorch-cuda=12.1
  - torchaudio
  - torchvision
  - onnx
  - onnxruntime
  - pip
  - pip:
    - onnxscript
